set -g default-terminal "tmux-256color"

set -g terminal-features[0] "xterm*:clipboard:ccolour:cstyle:focus:title"
set -g terminal-features[1] "screen*:title"
set -g terminal-features[2] "rxvt*:ignorefkeys"
set -g terminal-features[3] "xterm-256color:RGB"
set -g terminal-features[4] "alacritty:RGB"
set -g terminal-features[5] "xterm-kitty:RGB"

set -g terminal-overrides[0] "linux*:AX@"
set -g terminal-overrides[1] "xterm-256color:Tc"
set -g terminal-overrides[2] "alacritty:Tc"
set -g terminal-overrides[3] "xterm-kitty:Tc"
