"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_status\
$nodejs\
$c\
$rust\
$golang\
$php\
$java\
$kotlin\
$haskell\
$python\
$conda\
$docker_context\
$kubernetes\
${env_var.KUBECONFIG}\
\n\
$time\
$cmd_duration\
$status\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_bg_console='#000000'
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"
format = '[](fg:color_orange)[$symbol]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CachyOS = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[hostname]
disabled = false
ssh_only = false
format = '[ @ $hostname]($style)[ ](fg:color_orange)'
style = "bg:color_orange fg:color_fg0"

[localip]
ssh_only = false
format = '[](fg:color_orange)[ \($localipv4\)]($style)[ ](fg:color_orange)'
style = "bg:color_orange fg:color_fg0"
disabled = false

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[](fg:color_yellow)[ $path ]($style)[ ](fg:color_yellow)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[](fg:color_aqua)[ git $symbol $branch ](fg:color_fg0 bg:color_aqua)'

[git_status]
style = "bg:color_aqua"
format = '[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)[ ](fg:color_aqua)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[](fg:color_blue)[ $symbol( $version) ](fg:color_fg0 bg:color_blue)[ ](fg:color_blue)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[](fg:color_blue)[ $symbol( $version) ](fg:color_fg0 bg:color_blue)[ ](fg:color_blue)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[](fg:color_blue)[ $symbol( $version) ](fg:color_fg0 bg:color_blue)[ ](fg:color_blue)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[](fg:color_blue)[ $symbol( $version) ](fg:color_fg0 bg:color_blue)[ ](fg:color_blue)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[](fg:color_blue)[ $symbol( $version) ](fg:color_fg0 bg:color_blue)[ ](fg:color_blue)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[](fg:color_blue)[ $symbol( $version) ](fg:color_fg0 bg:color_blue)[ ](fg:color_blue)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[](fg:color_blue)[ $symbol( $version) ](fg:color_fg0 bg:color_blue)[ ](fg:color_blue)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[](fg:color_blue)[ $symbol( $version) ](fg:color_fg0 bg:color_blue)[ ](fg:color_blue)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[](fg:color_blue)[ $symbol( $version) ](fg:color_fg0 bg:color_blue)[ ](fg:color_blue)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[](fg:color_bg3)[ $symbol( $context) ](fg:#83a598 bg:color_bg3)[ ](fg:color_bg3)'

[conda]
style = "bg:color_bg3"
format = '[](fg:color_bg3)[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)[ ](fg:color_bg3)'

[time]
disabled = false
time_format = "%a %d %B %y   %R"
style = "bg:color_bg1"
format = '[](fg:color_bg1)[  $time ](fg:color_fg0 bg:color_bg1)[ ](fg:color_bg1)'

[cmd_duration]
min_time = 1000
style = "bg:color_bg3 fg:color_fg0"
format = '[](fg:color_bg3)[  $duration ]($style)[ ](fg:color_bg3)'

[status]
disabled = false
style = "bg:color_red fg:color_fg0"
symbol = ""
format = '[](fg:color_red)[ $symbol $status ]($style)[ ](fg:color_red)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[kubernetes]
disabled = false
detect_env_vars = ['KUBECONFIG']
style = "bg:color_bg1 fg:color_green"
format = '[](fg:color_bg1)[ $symbol $context( \($namespace\))]($style)[ ](fg:color_bg1)'

[env_var.KUBECONFIG]
style="bg:color_bg1 fg:color_green"
format='[](fg:color_bg1)[ $env_value]($style)[ ](fg:color_bg1)'
